todo/urls.py
from django.urls import path
from .views import ListTodo,TodoCreateView,TodoDeleteView,TodoUpdateView
from . import views
app_name='todo'
urlpatterns = [
    path('home/<int:user_id>/', ListTodo.as_view(),name='home'),
    path('new/', TodoCreateView.as_view(), name="create"),
    path('<int:pk>/delete/', TodoDeleteView.as_view(), name="delete"),
    path('<int:pk>/update/', TodoUpdateView.as_view(), name="update"),
    path('cross/<int:obj_id>/',views.cross_off,name='cross'),
    path('uncross/<int:obj_id>/',views.uncross,name='uncross'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name='users'
urlpatterns = [
    path('home/',views.home,name='home'),
    path('login/',views.CustomLoginView.as_view(),name='login'), #automatically renders registration/login.html page
    path('logout/',LogoutView.as_view(),name='logout'),  # automatically renders registration/logged_out.html page
    path('register/',views.register,name='register'),
    path('profile/', views.profile, name='profile'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404,handler500
from users import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('todo/',include('todo.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404=views.error_404
handler500=views.error_500

todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.shortcuts import reverse
# Create your models here.
class Todo(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    content=models.CharField(max_length=100)
    is_completed=models.BooleanField(default=False)
    date=models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse('todo:detail',kwargs={'pk':self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    CHOICES = (
        ('STUDENT', 'STUDENT'),
        ('EMPLOYEE', 'EMPLOYEE'),
        ('ENTREPRENEUR', 'ENTREPRENEUR'),
        ('OTHERS', 'OTHERS'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    location = models.CharField(max_length=30, blank=True)
    birthdate = models.DateField(null=True, blank=True)
    Occupation = models.CharField(choices=CHOICES, null=True, blank=True, max_length=15)
    image = models.ImageField(default='default.png', upload_to='profile_pics')
    bio = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.user.username} Profile'

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['location','birthdate','Occupation','bio','image']

todo/views.py
from django.shortcuts import render, reverse
from django.views import generic
from .models import Todo
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect


# Create your views here.

class ListTodo(LoginRequiredMixin, generic.ListView):
    model = Todo

    # template_name='todo_list.html' <model>_list.html(default) dont need to specify
    # context_object_name = object_list default
    def get_queryset(self):
        return Todo.objects.filter(user=self.kwargs['user_id'])


class TodoCreateView(LoginRequiredMixin,generic.CreateView):
    model = Todo
    fields = ['content']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('todo:home', kwargs={'user_id': self.request.user.id})


class TodoDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Todo

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        todo = self.get_object()
        if self.request.user == todo.user:
            return True
        return False

    def get_success_url(self):
        return reverse_lazy('todo:home', kwargs={'user_id': self.request.user.id})


class TodoUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Todo
    fields = ['content']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        todo = self.get_object()
        if self.request.user == todo.user:
            return True
        return False

    def get_success_url(self):
        return reverse_lazy('todo:home', kwargs={'user_id': self.request.user.id})


def cross_off(request, obj_id):
    todo = Todo.objects.get(id=int(obj_id))
    todo.is_completed = True
    todo.save()
    return HttpResponseRedirect(reverse('todo:home', kwargs={'user_id': request.user.id}))


def uncross(request, obj_id):
    todo = Todo.objects.get(id=int(obj_id))
    todo.is_completed = False
    todo.save()
    return HttpResponseRedirect(reverse('todo:home', kwargs={'user_id': request.user.id}))

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required

from .forms import UserRegisterForm
from django.contrib import messages
from .forms import UserUpdateForm, ProfileUpdateForm


# Create your views here.
def home(request):
    return render(request, 'registration/home.html')


# used to show success_message
class CustomLoginView(SuccessMessageMixin, LoginView):
    # template_name='users/login.html not needed by default it will look for registration/login.html
    success_message = "You were successfully logged in"
    success_url = '/'
    # LOGIN_REDIRECT_URL Specified in settings
    # crispy forms will not work without bootstrap
    """def get_success_url(self):   # can be used instead of LOGIN_REDIRECT_URL In settings
        return '/'"""


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            form.save()
            messages.success(request, f'Account created succesfully for {username}')
            return redirect('users:login')
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})

@login_required(login_url='/user/login/')
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('users:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    return render(request, 'registration/profile.html', {'u_form': u_form, 'p_form': p_form})


def error_404(request, exception):
    return render(request, 'registration/error_404.html')


def error_500(request):
    return render(request, 'registration/error_404.html')

todo/templates/todo/todo_confirm_delete.html
{% extends 'registration/base.html' %}
{% block content %}
    <div class="container text-center">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mg-4 text-center">Delete Todo</legend>
                <h2>Are you sure you want to delete?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes,Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'todo:home' user.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

todo/templates/todo/todo_form.html
{% extends 'registration/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<body>
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'todo:home' user.id %}">Home <span class="sr-only">(current)</span></a>
      </li>
        {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'todo:home' user.id %}">Todo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="">Blog</a>
            </li>
             <li class="nav-item">
                <a class="nav-link" href="">Polls</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Register</a>
            </li>
        {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <div class="container text-center" id="todoadd">
        <div class="text-center">
            <strong style="font-size:30px;border-bottom:2px solid MediumSeaGreen;" >Todo</strong>
        </div><br>
        <form method="post">
            {% csrf_token %}
            <div class="form-label-group">
                {{form|crispy}}
            </div>
             <button class="btn btn-lg btn-primary btn-block" type="submit">Add</button>
        </form>
    </div>
</body>
{% endblock %}

todo/templates/todo/todo_list.html
{% extends 'registration/base.html' %}
{% block content %}
<body class="loginbackground">
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
        {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'todo:home' user.id %}">Todo</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'todo:create' %}">Add+</a>
            </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Register</a>
            </li>
        {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% if object_list.first %}
<div class="container" style="margin-top:100px;">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover ">
                <thead>
                    <tr style="color:#ffffff;text-align:center;">

                            <th>No</th>
                            <th>Content</th>
                            <th>Completed</th>
                            <th>Date Created</th>
                            <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                        {% for obj in object_list %}

                            {% if obj.is_completed %}
                                <tr  class=" bg-light text-success text-center">
                                    <td>{{forloop.counter}}</td>
                                    <td title="click here to edit"><a style="color:green;" href="{% url 'todo:update' obj.id %}">{{obj.content}}</a></td>
                                    <td title="click here"><a class="text-success" href="{% url 'todo:uncross' obj.id %}">Yes</a></td>
                                    <td>{{obj.date|date:"F d, Y"}}</td>
                                    <td title="click here to delete"><a style="color:#000000;" href="{% url 'todo:delete' obj.id %}">Delete</a></td>
                                </tr>
                            {% else %}
                                <tr class="bg-danger text-center">
                                    <td>{{forloop.counter}}</td>
                                    <td title="click here to edit"><a class="text-light" href="{% url 'todo:update' obj.id %}">{{obj.content}}</a></td>
                                    <td title="click here"><a style="color:#ffffff;" href="{% url 'todo:cross' obj.id %}">No</a></td>
                                    <td>{{obj.date|date:"F d, Y"}}</td>
                                    <td title="click here to delete"><a style="color:#000000;" href="{% url 'todo:delete' obj.id %}">Delete</a></td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                </tbody>
            </table>
        </div>
</div>
{% else %}
    <div class="jumbotron text-center">
        <p>Add Todo to show here</p>
        <a class="btn btn-success" href="{% url 'todo:create' %}">Add</a>
    </div>
{% endif %}
</body>
{% endblock %}